
x-canillitabot-base: &canillitabot-base
  build:
    context: .
    cache_from:
      - canillitabot:latest
  image: canillitabot:latest
  restart: unless-stopped
  env_file: .env
  environment:
    - REDIS_URL=redis://redis:6379/0
  networks:
    - canillitabot-network
  volumes:
    - data:/app/data
    - logs:/app/logs
    - ./config:/app/config:ro

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - canillitabot-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  canillitabot:
    <<: *canillitabot-base
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.path.insert(0, '/app/src'); from database import Database; from config import Config; db = Database(Config()); print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  canillitabot-worker:
    <<: *canillitabot-base
    command: ["python", "src/worker.py"]
    depends_on:
      redis:
        condition: service_healthy
      canillitabot:
        condition: service_started
    healthcheck:
      test: ["CMD", "python", "-c", "import redis; r = redis.from_url('redis://redis:6379/0'); r.ping(); print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  dashboard:
    <<: *canillitabot-base
    command: ["python", "src/dashboard.py", "--host", "0.0.0.0", "--port", "5000"]
    ports:
      - "9000:5000"
    depends_on:
      - canillitabot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  canillitabot-network:
    driver: bridge

volumes:
  redis_data:
  data:
  logs:
