services:
  canillitabot:
    build: 
      context: .
      cache_from:
        - canillitabot:latest
    image: canillitabot:latest
    restart: unless-stopped
    environment:
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
      - REDDIT_USERNAME=${REDDIT_USERNAME}
      - REDDIT_PASSWORD=${REDDIT_PASSWORD}
      - REDDIT_USER_AGENT=${REDDIT_USER_AGENT}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - REDDIT_SUBREDDITS=${REDDIT_SUBREDDITS}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config:ro
    networks:
      - canillitabot-network
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.path.insert(0, '/app/src'); from database import Database; from config import Config; db = Database(Config()); print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  canillitabot-network:
    driver: bridge