reddit:
  check_interval: 30  # seconds between checks
  max_posts_per_check: 10

youtube:
  enabled: true  # Enable YouTube video processing
  summary_template: |
    # 🎥 {title}
    
    **Resumen del video:**
    {summary}
    
    ---
    
    *[Link al video]({url})*

    ^(CanillitaBot v1.0 - Resumiendo videos para hacerlos más accesibles.)

x_twitter:
  enabled: true  # Enable X/Twitter post processing
  comment_template: |
    # 🐦 {author} en X
    
    **{date}**
    
    {text}
    
    {media_note}
    
    ---
    
    *[Ver post original]({url})*

    ^(CanillitaBot v1.0 - Compartiendo contenido de X para hacerlo más accesible.)

bot:
  comment_template: |    
    # {title}
    
    {content}
    
    ---
    
    *[Link a la noticia]({url})*

    ^(CanillitaBot v1.0 - Compartiendo noticias para hacerlas más accesibles.)

  continuation_template: |
    {content}
  
  max_comment_length: 10000  # Reddit's comment limit
  max_article_length: 50000  # Maximum total article length to process
  min_article_length: 200     # characters

extraction:
  timeout: 15  # seconds
  max_retries: 3
  user_agent: "CanillitaBot/1.0 (News Bot)"

database:
  path: "data/processed_posts.db"
  cleanup_days: 30  # remove entries older than this

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/canillitabot.log"